[package]
name = "rurl"
version = "0.1.0"
authors = ["kujenga <git@ataylor.io>"]
edition = "2021"

[dependencies]
clap = "3.2"
reqwest = { version = "0.11", features = ["json"] }
http = "0.2"
tokio = { version = "1", features = ["full"] }
