[package]
name = "rurl"
version = "0.1.0"
authors = ["kujenga <git@ataylor.io>"]
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
http = "0.2"
tokio = { version = "1", features = ["full"] }
